### PR TITLE
Create database schema

### LINKED ISSUE #3: [2pts] Creating data model (group task)
Build the project schema by creating and running the necessary migration files following the ERD diagram.

### PR DESCRIPTION
**Pull request by Tshobohwa**
Hi @momo-87 ,
I'm requesting your review of the updates I made on our project in this milestone
## FEATURES ADDED
- Documented professionally the project in the readme file
- Created and runed the database migrations.

### CODE REVIEW

**Review by momo-87 — CHANGES_REQUESTED** [review]
# Status: INVALID PR 🔴 
Hi @Tshobohwa ,
You did a great job generating the migrations files and the corresponding schema file. 👏 👏  Unfortunately, I can not review your code because of a linter error. 

# Optional Suggestions 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers, and Happy coding 👨‍💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

#
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by Tshobohwa** [comment]
> # Status: INVALID PR 🔴
> Hi @Tshobohwa , You did a great job generating the migrations files and the corresponding schema file. 👏 👏 Unfortunately, I can not review your code because of a linter error.
> 
> # Optional Suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> Cheers, and Happy coding 👨‍💻
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

I actually tried to solve the linter error but I couldn't. it is coming from the CSS file, a side that I didn't touch, it seems like I don't have some authorization or something like that.

**Comment by momo-87** [comment]
> > # Status: INVALID PR 🔴
> > Hi @Tshobohwa , You did a great job generating the migrations files and the corresponding schema file. 👏 👏 Unfortunately, I can not review your code because of a linter error.
> > # Optional Suggestions
> > _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> > Cheers, and Happy coding 👨‍💻
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).
> 
> I actually tried to solve the linter error but I couldn't. it is coming from the CSS file, a side that I didn't touch, it seems like I don't have some authorization or something like that.

Very strange, we have not yet add any CSS file. Anyway, I'm gonna approve the PR, we will then have to solve it later.

**Review by momo-87 — APPROVED** [review]

**Comment by Tshobohwa** [comment]
Alright

**Pull request merged**
